/**
 * download-assets.mjs — fetches every asset in scripts/assets-manifest.json
 * (generated by port.mjs) from the Webflow CDN into public/. Skips files that
 * already exist; run with --force to re-download everything.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const manifest = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'scripts', 'assets-manifest.json'), 'utf8')
);
const force = process.argv.includes('--force');

const entries = Object.entries(manifest);
let ok = 0,
  skipped = 0,
  failed = [];

const CONCURRENCY = 8;
let i = 0;
async function worker() {
  while (i < entries.length) {
    const [local, remote] = entries[i++];
    const dest = path.join(ROOT, 'public', local);
    if (!force && fs.existsSync(dest) && fs.statSync(dest).size > 0) {
      skipped++;
      continue;
    }
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    try {
      const res = await fetch(remote);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const buf = Buffer.from(await res.arrayBuffer());
      fs.writeFileSync(dest, buf);
      ok++;
    } catch (err) {
      failed.push([local, remote, String(err)]);
    }
  }
}
await Promise.all(Array.from({ length: CONCURRENCY }, worker));
console.log(`downloaded ${ok}, skipped ${skipped}, failed ${failed.length}`);
for (const [local, remote, err] of failed) console.error(`FAILED ${local} <- ${remote}: ${err}`);
if (failed.length) process.exit(1);
